name: website publisher

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Built Script
      run: |
         chmod +x build.sh
         ./build
      shell: bash
